spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: test
          uri: lb://eureka-client
          predicates:
            - Path=/main/test
            - Method=GET
        - id: name
          uri: lb://eureka-client-2
          predicates:
            - Path=/new/name
            - Method=GET
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
